apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: k8s-agileng-io
spec:
  secretName: k8s-agileng-io
  issuerRef: 
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: k8s.agileng.io
  dnsNames:
    - k8s.agileng.io
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - k8s.agileng.io